eureka:
  instance:
    hostname: 3.15.7.235
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

spring:
  security:
    oauth2:
      client:
        registration:
          oauth2-client-credentials:
            auth-server-url: http://18.216.69.221:8080/
            provider: keycloak-provider
            client-id: ms-users-client
            scope: openid
            authorization-grant-type: client_credentials
            client-secret: ${KCK_USERS_CLIENT_SECRET:dVT1I4AoEevpq3b3pwIO6HnDFBMYfwIZ}
        provider:
          keycloak-provider:
            token-uri: http://18.216.69.221:8080/realms/DmhRealm/protocol/openid-connect/token
      resource-server:
        jwt:
          issuer-uri: http://18.216.69.221:8080/realms/DmhRealm
          jwk-set-uri: http://18.216.69.221:8080/realms/DmhRealm/protocol/openid-connect/certs

dmh:
  keycloak:
    server-url: http://18.216.69.221:8080/
    realm: DmhRealm
    client-id: ms-users-client
    client-secret: ${KCK_USERS_CLIENT_SECRET:dVT1I4AoEevpq3b3pwIO6HnDFBMYfwIZ}
    username: ${KCK_MASTER_USERNAME:admin}
    password: ${KCK_MASTER_PASSWORD:admin}

feign:
  circuitbreaker:
    enabled: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: Servico de usuários.
  author: Grupo 03
  severity: Alto

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    dateformat: 'dd-MM-yyyy HH:mm:ss.SSS'
    console: '%clr(%d{"dd-MM-yyyy''T''HH:mm:ss"}){faint} %highlight(%clr(${LOG_LEVEL_PATTERN:-%5p})) %clr(${PID:- })
    %clr(---){faint} %clr([%15.15t]){faint} %clr([%-40.40logger{39}]:%line){cyan} %clr(-){faint} %m%n%wEx'
